# Generated by Django 4.1.3 on 2022-12-13 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=20, verbose_name='Название')),
                ('clan_overall_balance', models.FloatField(default=0, verbose_name='Общий баланс клана')),
            ],
        ),
        migrations.CreateModel(
            name='PromoCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(max_length=8, verbose_name='Промокоды')),
                ('amount', models.TextField(max_length=20, verbose_name='Количество')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20, verbose_name='Никнэйм')),
                ('password', models.TextField(max_length=20, verbose_name='Пароль')),
                ('phone_number', models.TextField(verbose_name='Номер телефона')),
                ('tg_id', models.CharField(max_length=100, verbose_name='Телеграмм айди')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tier', models.CharField(choices=[('A', 'Admin'), ('U', 'User'), ('G', 'Gold'), ('S', 'Silver'), ('B', 'Bronze')], default='U', max_length=1)),
                ('clan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='server_app.clan')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(max_length=30, verbose_name='Баланс')),
                ('overall_balance', models.FloatField(default=100000, verbose_name='Общий баланс')),
                ('bitcoin', models.FloatField(default=0, verbose_name='Bitcoin')),
                ('ethereum', models.FloatField(default=0, verbose_name='Ethereum')),
                ('litecoin', models.FloatField(default=0, verbose_name='Litecoin')),
                ('binance_coin', models.FloatField(default=0, verbose_name='Binance Coin')),
                ('cardano', models.FloatField(default=0, verbose_name='Cardano')),
                ('solana', models.FloatField(default=0, verbose_name='Solana')),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='server_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, choices=[('BTC', 'bitcoin'), ('ETH', 'ethereum'), ('LIT', 'litecoin'), ('BNB', 'binance_coin'), ('CRD', 'cardano'), ('SOL', 'solana')], max_length=3, null=True)),
                ('date', models.DateTimeField(verbose_name='Дата оплаты')),
                ('sender', models.TextField(verbose_name='Отправитель')),
                ('recipient', models.TextField(verbose_name='Получатель')),
                ('amount_minus', models.TextField(verbose_name='Количество снятых средств')),
                ('amount_plus', models.TextField(verbose_name='Количество полученных средств')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='server_app.wallet')),
            ],
        ),
    ]
