# Generated by Django 4.1.3 on 2022-12-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ('users',)},
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='amount_plus',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'dollar'), ('BTC', 'bitcoin'), ('ETH', 'ethereum'), ('LIT', 'litecoin'), ('BNB', 'binance_coin'), ('CRD', 'cardano'), ('SOL', 'solana')], max_length=3, null=True),
        ),
    ]
