# Generated by Django 4.1.3 on 2022-12-17 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0003_alter_wallet_options_rename_balance_wallet_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='server_app.users'),
        ),
    ]
