# Generated by Django 4.1.3 on 2022-12-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0004_alter_wallet_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата оплаты'),
        ),
    ]
