# Generated by Django 4.1.3 on 2022-12-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0005_alter_transactions_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.TextField(max_length=100, verbose_name='Пароль'),
        ),
    ]
