# Generated by Django 4.1.3 on 2022-12-23 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0007_rename_currency_transactions_recipient_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='amount_minus',
            new_name='amount',
        ),
    ]
