# Generated by Django 4.1.3 on 2022-12-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0009_alter_transactions_recipient_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='amount',
        ),
        migrations.AddField(
            model_name='transactions',
            name='commission',
            field=models.FloatField(default=0, max_length=100, verbose_name='Комисиия'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='received_amount',
            field=models.FloatField(default=0, max_length=100, verbose_name='Полученно стредств'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='send_amount',
            field=models.FloatField(default=0, max_length=100, verbose_name='Отпраленно средств'),
        ),
    ]
