# Generated by Django 4.1.3 on 2023-01-04 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0010_remove_transactions_amount_transactions_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='clan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='server_app.clan'),
        ),
        migrations.AlterField(
            model_name='users',
            name='tier',
            field=models.CharField(choices=[('U', 'User'), ('B', 'Bronze'), ('S', 'Silver'), ('G', 'Gold'), ('A', 'Admin')], default='U', max_length=1),
        ),
    ]
