# Generated by Django 4.1.3 on 2023-01-05 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0011_alter_users_clan_alter_users_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='clan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='server_app.clan'),
        ),
    ]
