# Generated by Django 4.1.3 on 2023-01-10 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0012_alter_users_clan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='clan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='server_app.clan', verbose_name='Клан'),
        ),
        migrations.AlterField(
            model_name='users',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='users',
            name='tier',
            field=models.CharField(choices=[('U', 'User'), ('B', 'Bronze'), ('S', 'Silver'), ('G', 'Gold'), ('A', 'Admin')], default='U', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'dollar'), ('BTC', 'bitcoin'), ('ETH', 'ethereum'), ('ADA', 'cardano'), ('BNB', 'binance_coin'), ('XRP', 'xrp'), ('DOGE', 'dogecoin')], max_length=4, null=True, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='server_app.users', verbose_name='Владелец кошелька'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, choices=[('USD', 'dollar'), ('BTC', 'bitcoin'), ('ETH', 'ethereum'), ('ADA', 'cardano'), ('BNB', 'binance_coin'), ('XRP', 'xrp'), ('DOGE', 'dogecoin')], max_length=4, null=True, verbose_name='Валюта')),
                ('price', models.FloatField(max_length=100, verbose_name='Цена')),
                ('amount', models.FloatField(max_length=100, verbose_name='Количество')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выкладывания объявления')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='server_app.wallet')),
            ],
        ),
    ]
