# Generated by Django 4.1.3 on 2023-01-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0017_promocodes_currency_wallet_wallet_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='wallet_id',
            new_name='wallet_number',
        ),
    ]
